
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments


# Setup
timezone:            Europe/Moscow
locale:              ru
name:				         2a-lab
title:               2a Lab
tagline:             'tagline'
description:         'description'
url:                 2a-lab.ru
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 2a-lab
  
# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
